### ISSUE TITLE
Spanish locale does not recognize me.

### ISSUE THREAD

**Issue by juanjosesanchezesteban** [aavanzyl/ngx-tiny#15]
Hello,

I can't get the library to recognize my locale in Spanish. It takes the default option which is the name of the months and days in English.

My code is the following:

`import { Component, OnInit } from '@angular/core';
import { DatePickerOptions, NgxDatePickerComponent } from '@ngx-tiny/date-picker';

import { environment } from '../../../environments/environment';
import { es } from 'date-fns/locale'

@Component({
  selector: 'app-componentes',
  templateUrl: './componentes.component.html',
  styleUrls: ['./componentes.component.css']
})
export class ComponentesComponent implements OnInit {

  singleDate: Date = new Date();
  dateInstanceSingle: NgxDatePickerComponent;
  datePickerOptions: DatePickerOptions = { 
    locale: es,
    displayFormat: 'dd/MM/yyyy',
    barTitleFormat: 'MMMM yyyy',
    firstCalendarDay: 1
  };

  constructor() { }

  ngOnInit(): void {
  }

  onChangeSingle(value: Date): void {
    this.singleDate = value;
    console.log(this.singleDate);
  }

}
`

`<div style="padding-left: 20px">
<p>Componentes</p>

<input class="form-control" placeholder="Select date" [ngxDatePicker]="dateInstanceSingle" [value]="singleDate" (valueChange)="onChangeSingle($event)">
<ngx-date-picker #dateInstanceSingle [options]="datePickerOptions"></ngx-date-picker>

</div>`

**Comment by merliandrea** [comment]
You need to wrap the es inside a object

```
public datePickerOptions: DatePickerOptions = {
		locale: {locale: de},
		// ...
}
```

**Comment by juanjosesanchezesteban** [comment]
It works, thank you very much Andrea.
