### ISSUE TITLE
Can't get options `minDate` and `maxDate` working

### ISSUE THREAD

**Issue by muthiafi** [aavanzyl/ngx-tiny#3]
**Describe the bug**
Can't get options `minDate` and `maxDate`

**To Reproduce**
specify  `minDate` and `maxDate` on options

**Expected behavior**
the date that later than `maxDate `should be disabled 

after some investigation looks like a bug on function
`isDateSelectable(date: Date)`

**Comment by aavanzyl** [comment]
Hi @muthiafi 

Thanks for picking up this issue, I was able to reproduce it and made a fix. 
You can update to the latest version 8.0.6 of @ngx-tiny/date-picker to apply this changes.

If you are interested in the change, its as you said an issue with `isDateSelectable`:
https://github.com/aavanzyl/ngx-tiny/commit/52a867042fd126e0c50792a86e61a0afe53bc70f#diff-8983d116180b8d5823d4f675f05dfbec

ps, ignore the version 8.0.5, its meant to be 8.0.6 :) typo
