### ISSUE TITLE
Fatal typo on project home page

### ISSUE THREAD

**Issue by aunkrig** [aavanzyl/ngx-tiny#4]
https://aavanzyl.github.io/ngx-tiny/project/date-picker says:

    To install this library, run:
    npm install @ngx-tiny/ngx-date-picker --save

That produces a 404. The correct command line is

    npm install @ngx-tiny/date-picker --save

**Comment by jonathan-chin** [comment]
can confirm. was trying to install this and luckily I checked the issues here.

**Comment by aavanzyl** [comment]
I have corrected the typo, thanks for pointing it out. 

Also, can you indicate if you received any errors around:
`it's also important to note that the variables should be set before importing the theme file`

Variables should have a default value, was the issue that you could not specify any changes to the theme without having them first?

**Comment by jonathan-chin** [comment]
@aavanzyl my first instinct is to put all my imports at the top of the file.
if you look at the styling tab for the time picker, it's clear that the import happens at the bottom of the variable definitions.
however, if you look at the styling tab for the date picker, there's no import line. therefore, I assumed I should import at the top of the file.

(by the way, these two are awesome projects. I've been searching for a good date and time picker that's also easily styleable for literally years)

**Comment by aavanzyl** [comment]
@jonathan-chin Thanks for the input, I have updated the docs to reflect this.
