### ISSUE TITLE
sass variable for previous month dates on hover

### ISSUE THREAD

**Issue by jonathan-chin** [aavanzyl/ngx-tiny#6]
for days that are in the current month, there are variables to change the foreground color on hover. this is useful if my hover background is a dark color and I need to switch the foreground to a light color.

however, there's no way to style the foreground color on hover for days that are not in the current months. by these, I mean the dates that would excluded if `{includeDays: 'none'}`. however, these days are still affected by the hover background. so I get dark on dark colors.

**Comment by aavanzyl** [comment]
@jonathan-chin I have updated the scss to handle the hover state on out of range month days, you can find the change in the latest version. Let me know if this works for you.
