### ISSUE TITLE
date-picker valueChange emits twice

### ISSUE THREAD

**Issue by jonathan-chin** [aavanzyl/ngx-tiny#8]
I was trying to debug this on my side but it seems that (valueChange) gets emitted twice.

looking at the website documentation and running the live example there, I see it also gets triggered twice:

```
// https://aavanzyl.github.io/ngx-tiny/project/date-picker
Wed Jan 08 2020 00:00:00 GMT-0500 (Eastern Standard Time)
Wed Jan 08 2020 00:00:00 GMT-0500 (Eastern Standard Time)
Sat Jan 11 2020 00:00:00 GMT-0500 (Eastern Standard Time)
Sat Jan 11 2020 00:00:00 GMT-0500 (Eastern Standard Time)
```

is this a side effect of something else? can this be avoided at all?

**Comment by JLNNN** [comment]
I'm experiencing the same behaviour.

**Comment by aavanzyl** [comment]
@JLNNN & @jonathan-chin This has been addressed in the latest version

**Comment by JLNNN** [comment]
confirmed, thank you!
