### ISSUE TITLE
Can't switch months with angular 10

### ISSUE THREAD

**Issue by JLNNN** [aavanzyl/ngx-tiny#9]
**Describe the bug**
If I click the "prev month" or "next month" buttons, the datepicker overlay just closes.

**To Reproduce**
1. installed npm packages as required
2. setup everything as described in docs
3. Click on datepicker input field
4. click on prev or next month buttons
5. See error

**Expected behavior**
The overlay switches to the previous or next month.

**Versions (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome 84.0.4147.135
 - Package Version [e.g. 1.2.3]: 8.0.6 (tried ^8.0.0)
 - Angular Version [e.g. 7.x]: 10

**Additional context**
It's working in your examples 🤷‍♂️

**Comment by aavanzyl** [comment]
I am in the process of upgrading the angular version to 10, might have something todo around this, Will release this tomorrow, keep you posted.

**Comment by aavanzyl** [comment]
@JLNNN I have published the latest version, now ready for Angular 10, please test and let me know if the issue is resolved.

**Comment by JLNNN** [comment]
@aavanzyl I updated to v10.0.1 and the problem is still existing. I can't switch months.

**Comment by JLNNN** [comment]
Since I don't know if GitHub sends notifications for closed issues, here's a heads-up @aavanzyl.

**Comment by JLNNN** [comment]
@aavanzyl Do you get notifications in closed issues?
